### ISSUE TITLE
Bonded/Unbonded ratio of 67% + Combined liquid/illiquid rewards

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/cosmos-economics#15]
Rewards to be provided 67% illiquid and 33% liquid continuously.

Main Reasons: 
1) The validator rewards should enforce the equilibrium of 67% bonded/unbonded ratio
2) Validators should receive something more or less consistent (aka this is opposed to providing 100% illiquid if below 67% and 0% if above 67%)

**Comment by rigelrozanski** [comment]
Pool Decision

**Comment by sunnya97** [comment]
This has been overturned in favor of fully bonded due to computational/conceptual complexity, correct?

**Comment by rigelrozanski** [comment]
Thanks, correct this has been overturned all rewards to be bonded (illiquid)
